`// This file was generate from a template using t2c
 // Source file : src/templates/template.t2c 
 // `
template = (ctx) ->
  output = ''
  output += "// This code was generated by a tool. Please modify with caution.\n"
  output += "//\n"
  output += "\n"
  output += "using System;\n"
  output += "\n"
  output += "namespace TLS\n"
  output += "{\n"
  
  for e in ctx.enums
    z = []
    for v in e.values 
      z.push "tls_#{v.name}=#{v.value}"
  
    output += "  public enum #{e.name}Enum { #{z.join(',')} };\n"
    output += "  public class #{e.name}\n"
    output += "  {\n"
    output += "    public #{e.name}Enum value;\n"
    output += "    public int num_bytes = 1;\n"
    output += "\n"
    output += "    public int Load(byte[] buffer,long offset) {\n"
    output += "      long value;\n"
    output += "      BufferTools.ReadNumberFromBuffer(buffer,offset,num_bytes,out value);\n"
    output += "      if(Enum.IsDefined(typeof(#{e.name}Enum), value)) {\n"
    output += "        this.value = (#{e.name}Enum)value;\n"
    output += "      }\n"
    output += "      return num_bytes;\n"
    output += "    }\n"
  
  
    output += "  }\n"
    output += "\n"
  
  for c in ctx.structs
    fields = []
    for f in c.fields
      fields.push "public #{f.type.name} #{f.name} = new #{f.type.name}();"
  
    output += "  public class #{c.name}\n"
    output += "  {\n"
  
    for f in fields
      output += "    #{f}\n"
  
  
    output += "    public long Load(byte[] buffer,long offset) {\n"
    output += "      long new_offset = offset;\n"
  
    for f in c.fields
      output += "      new_offset = #{f.name}.Load(buffer,new_offset);\n"
  
    output += "      return new_offset;\n"
    output += "    }\n"
    output += "  }\n"
  
  output += "}\n"
  
  
  
  
module.exports = template